/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type CollectionReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "collection";
};

export type Order = {
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  customer?: {
    name?: string;
    email?: string;
    phone?: string;
  };
  shippingAddress?: {
    state?: string;
    address?: string;
  };
  order?: {
    items?: Array<
      {
        _key: string;
      } & CollectionReference
    >;
    total?: number;
    currency?: "NGN";
    status?: "pending" | "paid" | "shipped" | "delivered";
    createdAt?: string;
  };
  payment?: {
    reference?: string;
    status?: "pending" | "success" | "failed";
  };
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Collection = {
  _id: string;
  _type: "collection";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  artist?: string;
  artImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  price?: {
    amount?: number;
    currency?: "NGN";
  };
  isSold?: boolean;
  dimensions?: {
    width?: number;
    height?: number;
    unit?: "cm" | "in";
  };
  available?: boolean;
  creationDate?: string;
  about?: BlockContent;
  reservedUntil?: string;
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
  listItem?: "bullet";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | CollectionReference
  | Order
  | SanityImageAssetReference
  | Collection
  | BlockContent
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/lib/queries.ts
// Variable: HOME_QUERY
// Query: {  "newPostImages": *[_type == "collection"]    | order(_createdAt desc)[0...4]{      _id,      "image": {        "url": artImage.asset->url,        "alt": artImage.alt      }    },  "HomePageCollections": *[_type == "collection"]| order(_createdAt desc)[0...4]{    name,    "slug": slug.current,    price{      amount,      currency    },    creationDate,    about,    "image": {      "url": artImage.asset->url,      "alt": artImage.alt    }  }}
export type HOME_QUERY_RESULT = {
  newPostImages: Array<{
    _id: string;
    image: {
      url: string | null;
      alt: string | null;
    };
  }>;
  HomePageCollections: Array<{
    name: string | null;
    slug: string | null;
    price: {
      amount: number | null;
      currency: "NGN" | null;
    } | null;
    creationDate: string | null;
    about: BlockContent | null;
    image: {
      url: string | null;
      alt: string | null;
    };
  }>;
};

// Source: sanity/lib/queries.ts
// Variable: COLLECTIONS
// Query: {  "collections": *[_type == "collection"]    | order(_createdAt desc)[$start...$end]{      _id,      name,      artist,      "slug": slug.current,      price{        amount,        currency      },      creationDate,      about,      "image": {        "url": artImage.asset->url,        "alt": artImage.alt      }    },  "total": count(*[_type == "collection"])}
export type COLLECTIONS_RESULT = {
  collections: Array<{
    _id: string;
    name: string | null;
    artist: string | null;
    slug: string | null;
    price: {
      amount: number | null;
      currency: "NGN" | null;
    } | null;
    creationDate: string | null;
    about: BlockContent | null;
    image: {
      url: string | null;
      alt: string | null;
    };
  }>;
  total: number;
};

// Source: sanity/lib/queries.ts
// Variable: ART_DETAILS
// Query: *[_type == "collection" && slug.current == $slug][0]{  _id,  _rev,  name,  about,  dimensions,  available,  reservedUntil,  artist,  price{    amount,    currency  },  "image": {    "url": artImage.asset->url,    "alt": artImage.alt  },  creationDate,  }
export type ART_DETAILS_RESULT = {
  _id: string;
  _rev: string;
  name: string | null;
  about: BlockContent | null;
  dimensions: {
    width?: number;
    height?: number;
    unit?: "cm" | "in";
  } | null;
  available: boolean | null;
  reservedUntil: string | null;
  artist: string | null;
  price: {
    amount: number | null;
    currency: "NGN" | null;
  } | null;
  image: {
    url: string | null;
    alt: string | null;
  };
  creationDate: string | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: PROCESSED_ORDER
// Query: *[_type == "order" && payment.reference == $reference][0]{    _id,    }
export type PROCESSED_ORDER_RESULT = {
  _id: string;
} | null;

// Source: sanity/lib/queries.ts
// Variable: ORDER_BY_REFERENCE
// Query: *[_type == "order" && payment.reference == $reference][0]{  customer{ name, email },  order{    "items": items[]->{      name,      artist,      "slug": slug.current,      "image": { "url": artImage.asset->url, "alt": artImage.alt }    },    total,    currency,    status,    createdAt  },  payment{ reference, status }}
export type ORDER_BY_REFERENCE_RESULT = {
  customer: {
    name: string | null;
    email: string | null;
  } | null;
  order: {
    items: Array<{
      name: string | null;
      artist: string | null;
      slug: string | null;
      image: {
        url: string | null;
        alt: string | null;
      };
    }> | null;
    total: number | null;
    currency: "NGN" | null;
    status: "delivered" | "paid" | "pending" | "shipped" | null;
    createdAt: string | null;
  } | null;
  payment: {
    reference: string | null;
    status: "failed" | "pending" | "success" | null;
  } | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n{\n  "newPostImages": *[_type == "collection"]\n    | order(_createdAt desc)[0...4]{\n      _id,\n      "image": {\n        "url": artImage.asset->url,\n        "alt": artImage.alt\n      }\n    },\n\n  "HomePageCollections": *[_type == "collection"]| order(_createdAt desc)[0...4]{\n    name,\n    "slug": slug.current,\n    price{\n      amount,\n      currency\n    },\n    creationDate,\n    about,\n    "image": {\n      "url": artImage.asset->url,\n      "alt": artImage.alt\n    }\n  }\n}\n': HOME_QUERY_RESULT;
    '\n{\n  "collections": *[_type == "collection"]\n    | order(_createdAt desc)[$start...$end]{\n      _id,\n      name,\n      artist,\n      "slug": slug.current,\n      price{\n        amount,\n        currency\n      },\n      creationDate,\n      about,\n      "image": {\n        "url": artImage.asset->url,\n        "alt": artImage.alt\n      }\n    },\n  "total": count(*[_type == "collection"])\n}\n': COLLECTIONS_RESULT;
    '*[_type == "collection" && slug.current == $slug][0]{\n  _id,\n  _rev,\n  name,\n  about,\n  dimensions,\n  available,\n  reservedUntil,\n  artist,\n  price{\n    amount,\n    currency\n  },\n  "image": {\n    "url": artImage.asset->url,\n    "alt": artImage.alt\n  },\n  creationDate,\n  }': ART_DETAILS_RESULT;
    '*[_type == "order" && payment.reference == $reference][0]{\n    _id,\n    }\n': PROCESSED_ORDER_RESULT;
    '\n*[_type == "order" && payment.reference == $reference][0]{\n  customer{ name, email },\n  order{\n    "items": items[]->{\n      name,\n      artist,\n      "slug": slug.current,\n      "image": { "url": artImage.asset->url, "alt": artImage.alt }\n    },\n    total,\n    currency,\n    status,\n    createdAt\n  },\n  payment{ reference, status }\n}\n': ORDER_BY_REFERENCE_RESULT;
  }
}
