/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Order = {
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  customer?: {
    name?: string;
    email?: string;
    phone?: string;
  };
  shippingAddress?: {
    state?: string;
    address?: string;
  };
  order?: {
    items?: Array<{
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      _key: string;
      [internalGroqTypeReferenceTo]?: "collection";
    }>;
    total?: number;
    currency?: "NGN";
    status?: "pending" | "paid" | "shipped" | "delivered";
    createdAt?: string;
  };
  payment?: {
    reference?: string;
    status?: "success" | "failed";
  };
};

export type Collection = {
  _id: string;
  _type: "collection";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  artist?: string;
  artImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  price?: {
    amount?: number;
    currency?: "NGN" | "USD" | "EUR";
  };
  dimensions?: {
    width?: number;
    height?: number;
    unit?: "cm" | "in";
  };
  available?: boolean;
  creationDate?: string;
  about?: BlockContent;
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
  listItem?: "bullet";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = Order | Collection | BlockContent | SanityImageCrop | SanityImageHotspot | Slug | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/lib/queries.ts
// Variable: HOME_QUERY
// Query: {  "newPostImages": *[_type == "collection"]    | order(_createdAt desc)[0...4]{      _id,      "image": {        "url": artImage.asset->url,        "alt": artImage.alt      }    },  "HomePageCollections": *[_type == "collection"]| order(_createdAt desc)[0...4]{    name,    "slug": slug.current,    price{      amount,      currency    },    creationDate,    about,    "image": {      "url": artImage.asset->url,      "alt": artImage.alt    }  }}
export type HOME_QUERYResult = {
  newPostImages: Array<{
    _id: string;
    image: {
      url: string | null;
      alt: string | null;
    };
  }>;
  HomePageCollections: Array<{
    name: string | null;
    slug: string | null;
    price: {
      amount: number | null;
      currency: "EUR" | "NGN" | "USD" | null;
    } | null;
    creationDate: string | null;
    about: BlockContent | null;
    image: {
      url: string | null;
      alt: string | null;
    };
  }>;
};
// Variable: ART_DETAILS
// Query: *[_type == "collection" && slug.current == $slug][0]{  name,  about,  dimensions,  available,  artist,  price{    amount,    currency  },  "image": {    "url": artImage.asset->url,    "alt": artImage.alt  },  creationDate,  }
export type ART_DETAILSResult = {
  name: string | null;
  about: BlockContent | null;
  dimensions: {
    width?: number;
    height?: number;
    unit?: "cm" | "in";
  } | null;
  available: boolean | null;
  artist: string | null;
  price: {
    amount: number | null;
    currency: "EUR" | "NGN" | "USD" | null;
  } | null;
  image: {
    url: string | null;
    alt: string | null;
  };
  creationDate: string | null;
} | null;
// Variable: COLLECTIONS
// Query: {  "collections": *[_type == "collection"]    | order(_createdAt desc)[$start...$end]{      name,      artist,      "slug": slug.current,      price{        amount,        currency      },      creationDate,      about,      "image": {        "url": artImage.asset->url,        "alt": artImage.alt      }    },  "total": count(*[_type == "collection"])}
export type COLLECTIONSResult = {
  collections: Array<{
    name: string | null;
    artist: string | null;
    slug: string | null;
    price: {
      amount: number | null;
      currency: "EUR" | "NGN" | "USD" | null;
    } | null;
    creationDate: string | null;
    about: BlockContent | null;
    image: {
      url: string | null;
      alt: string | null;
    };
  }>;
  total: number;
};

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n{\n  \"newPostImages\": *[_type == \"collection\"]\n    | order(_createdAt desc)[0...4]{\n      _id,\n      \"image\": {\n        \"url\": artImage.asset->url,\n        \"alt\": artImage.alt\n      }\n    },\n\n  \"HomePageCollections\": *[_type == \"collection\"]| order(_createdAt desc)[0...4]{\n    name,\n    \"slug\": slug.current,\n    price{\n      amount,\n      currency\n    },\n    creationDate,\n    about,\n    \"image\": {\n      \"url\": artImage.asset->url,\n      \"alt\": artImage.alt\n    }\n  }\n}\n": HOME_QUERYResult;
    "*[_type == \"collection\" && slug.current == $slug][0]{\n  name,\n  about,\n  dimensions,\n  available,\n  artist,\n  price{\n    amount,\n    currency\n  },\n  \"image\": {\n    \"url\": artImage.asset->url,\n    \"alt\": artImage.alt\n  },\n  creationDate,\n  }": ART_DETAILSResult;
    "\n{\n  \"collections\": *[_type == \"collection\"]\n    | order(_createdAt desc)[$start...$end]{\n      name,\n      artist,\n      \"slug\": slug.current,\n      price{\n        amount,\n        currency\n      },\n      creationDate,\n      about,\n      \"image\": {\n        \"url\": artImage.asset->url,\n        \"alt\": artImage.alt\n      }\n    },\n  \"total\": count(*[_type == \"collection\"])\n}\n": COLLECTIONSResult;
  }
}
