import type { Metadata } from "next";
import { Anton } from "next/font/google";
import { ThemeProvider } from "@/providers/theme-providers";
import AuthProvider from "@/providers/auth-provider";
import "./globals.css";
import { Footer } from "./_components/footer";

const anton = Anton({
  variable: "--font-anton",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "B-Arts-Gallery",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={`${anton.variable} antialiased`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}

            <Footer />
          </ThemeProvider>
        </body>
      </html>
    </AuthProvider>
  );
}
